image:
- Visual Studio 2017
- Ubuntu

#environment:
#  MINGW_DIR: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin

#clone_depth: 3

#build: off

init:
#- cmd: set PATH=%MINGW_DIR%;%PATH%
#- sh: sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test" > /dev/null
#- sh: sudo apt-get -yq update > /dev/null
#- sh: sudo apt-get install -yq --no-install-suggests --no-install-recommends gfortran-6 > /dev/null
#- sh: export FC=/usr/bin/gfortran-6
  
install:
- cmd: ECHO this is batch
- ps: Write-Host "This is PowerShell"
- cmd: gfortran --version
- sh: ECHO this is shell
- sh: gfortran --version

#- cmd: cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" ..
#- sh: cmake ..
#
#- cmake --build .
- make --version
- make all
#test_script: ctest -V

artifacts:
  - path: build/bin
    name: WASA-SED executable
	type: zip
	
deploy:
- provider: Environment
  name: production
  on:
    branch: unit_sedigraph # only this will work
#    APPVEYOR_REPO_TAG: true # condition will never be evaluated for annotated tag